### ISSUE TITLE
Return to Top in HTML5 themes

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-edits#1]
When Simple Edits is installed, the Return to top link is added to the footer. However, the link doesn't work because #wrap doesn't exist.

If we could either filter the output so the link is just # or remove the `[footer_backtotop]` shortcode for HTML5 themes.

**Comment by nathanrice** [comment]
https://github.com/copyblogger/genesis/commit/87635333d6ec6548da798eb9999192fcebb3ec29
