### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by kimparsell** [copyblogger/genesis-simple-edits#2]
We received a report in a ticket yesterday regarding an activation error message the customer was seeing:

> The plugin generated 153 characters of unexpected output during activation. If you notice "headers already sent" messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

I did some testing and can reproduce the error - test results below:

**Local XAMPP install (3.8.1 single, no plugins, Genesis 2.0.2 activated, php 5.4.17):**

Download plugin, no errors.

Activate plugin:

> The plugin generated 207 characters of unexpected output during activation. If you notice "headers already sent" messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Go to Genesis > Simple Edits:
- Remove post info line works.
- Remove post meta line works.
- Remove footer content works.

**HostGator install (3.8.1 single, clean install, no plugins, Genesis 2.0.2 activated, php 5.2.17):**

Download plugin, no errors.

Activate plugin:

> The plugin generated 215 characters of unexpected output during activation. If you notice "headers already sent" messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Go to Genesis > Simple Edits:
- Remove post info line works.
- Remove post meta line works.
- Remove footer content works.

**Comment by nathanrice** [comment]
50380b6
